title: Brenda Ramirez
email: brendarosaramirez@gmail.com
baseurl: ""

theme: minima

header_pages:
  - research_projects.md
  - publications.md
  - outreach.md
  - cv.md

footer_text: "brendarosaramirez@gmail.com"
