title: Brenda Ramirez
email: brendarosaramirez@gmail.com
description: Research Technician at the Moore [Laboratory of Zoology](https://moorelab.oxy.edu/) working on the [Free-Flying Los Angeles Parrot Project (FLAPP)](https://www.inaturalist.org/projects/free-flying-los-angeles-parrot-project)
baseurl: ""

theme: minima

header_pages:
  - research_projects.md
  - publications.md
  - outreach.md
  - cv.md
