title: Brenda Ramirez
author: Brenda R.
email: brendarosaramirez@gmail.com
description:
baseurl: ""
url: "https://brendarramirez.github.io"

theme: minima

header_pages:
  - Research Projects
  - Publications
  - Outreach
  - CV
